### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Aditya753b**
how abt this one? any other suggestions?

### CODE REVIEW

**Review by sammaji — CHANGES_REQUESTED** [review]
`npm install -g yarn` is for installing yarn

`yarn install` or just `yarn` is the command for installing all the packages

Add both

**Comment by sammaji** [comment]
Also, why did you close the previous PR. Just update the code in your repository. That will automatically update the PR

**Review by sammaji — APPROVED** [review]
Look good.

**Comment by sammaji** [comment]
Hey @Aditya753b , thanks for your contribution (fixed issue #3). If you want to work on something else or need any help, let me know ✌️

**Comment by adityakusetti** [comment]
sure and I'm willing to work on other issues too 👍

**Pull request merged**
